config/routes.rb
Rails.application.routes.draw do
  resources :blocks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'blocks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/block.rb
class Block < ApplicationRecord
  after_create_commit { broadcast_append_to 'blocks' }
  after_update_commit { broadcast_replace_to 'blocks' }
  after_destroy_commit { broadcast_remove_to 'blocks' }

  validates :type_of_block, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: %i[update destroy]

  # GET /blocks or /blocks.json
  def index
    @blocks = Block.all
  end

  # POST /blocks
  def create
    @block = Block.new(block_params)

    @block.save
  end

  # PATCH/PUT /blocks/1
  def update
    @block.update(block_params)
  end

  # DELETE /blocks/1
  def destroy
    @block.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_block
    @block = Block.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def block_params
    params.require(:block).permit(:text, :type_of_block)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
  BLOCKS = {
    'Heading 1' => { placeholder: 'Heading 1' },
    'paragraph' => { placeholder: 'Type / for blocks @ to link docs or people or Backspace to delete' }
  }.freeze

  def block_object(block_type)
    BLOCKS[block_type]
  end

  def blocks
    BLOCKS
  end
end

app/views/blocks/_block.html.erb
<%= turbo_frame_tag dom_id(block), data: {controller: 'block'}, class: 'relative' do %>
  <%= form_with(model: block, class: "contents relative" ) do |form| %>
    <div 
      id="<%= dom_id block %>"
      class="<%= block.type_of_block.sub(/ /, '-') %> block w-full p-4 outline-none focus:bg-gray-100"
      contenteditable
      placeholder="<%= block_object(block.type_of_block)[:placeholder] %>"
      data-action="keydown->block#press input->block#changed keyup->block#input focusin->block#focusIn focusout->block#focusOut"
      data-block-target="content"
    ><%= block.text if block.text.length > 0 %></div>
    <span class="absolute top-1/2 -translate-y-1/2 right-10 z-10" data-show="false" data-block-target="enter">&#9166;</span>
    <%= form.hidden_field :text, data: {block_target: 'input'} %>
    <%= form.hidden_field :type_of_block, data: {block_target: 'type'} %>
  <% end %>
    <div 
      data-show="false"
      data-block-target="dropdown"
      class="flex flex-col border p-1 absolute z-10 top-100 left-0 bg-white rounded shadow"
    >
      <h5>BASIC BLOCKS</h5>
      <% blocks.each do |block| %>
        <%= content_tag(:button, data: {action: 'click->block#updateType', selected: false}, class: 'py-4 hover:bg-slate-400') do%>
          <span><%= block[0] %></span>
        <% end %>
      <% end %>
      <p class="font-bold p-4" data-show="false">Not found</p>
    </div>
    <%= button_to '', block_path(block), method: 'delete', data: {block_target: 'delete'}, class: 'hidden' %>
    <%= render 'blocks/form', data: {block_target: 'newInput'}%>
<% end %>

app/views/blocks/_form.html.erb
<%= form_with(model: Block.new, class:'hidden') do |form| %>
  <%= form.hidden_field :text, data: %>
  <%= form.hidden_field :type_of_block %>
  <button type="submit">submit</button>
<% end %>

app/views/blocks/index.html.erb
<div class="w-full flex flex-col">
  <div class="flex justify-between items-center ">
    <h1 class="font-bold text-4xl">Notion</h1>
  </div>

  <div 
      id="blocks" 
      class="max-w-screen-md w-4/6 h-full cursor-text self-center border-x p-3"
      data-test="blocks"
      data-controller="container"
      data-action="click->container#clicked"
  >
    <%= turbo_stream_from "blocks" %>
    <%= turbo_frame_tag "blocks", data: {container_target: 'container'}  do %>
      <%= render @blocks %>
    <% end %>
    <%= render 'form', data: {container_target: 'newInput'}%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container min-h-screen mx-auto p-5 flex">
      <%= yield %>
    </main>
  </body>
</html>